from langchain_openai import ChatOpenAI
from browser_use import Agent
from dotenv import load_dotenv
load_dotenv()

import asyncio

llm = ChatOpenAI(model="gpt-4.1")

async def main():
    agent = Agent(
        task="""
         Visit https://thedistrictdocklands.com.au/. For each store in the list below, do this. 1. On the main website link provided, there are 6 Sections, namely: Play, Eat, Shop, Stay, Local and Hub. Click on any which will open up a list of stores. 
         2. Click on each store to get the link, short general description, opening hours and the floor it is located on. 3. Return the information in a JSON format
            [
                {"name": "Ally Fashion", "floor": "Ground"},
                {"name": "Alpaka Gear", "floor": "Ground"},
                {"name": "Archie Brothers Cirque Electric", "floor": "Ground"},
                {"name": "Artvo", "floor": "Ground"},
                {"name": "Bonds", "floor": "Ground"},
                {"name": "Boost Juice", "floor": "Ground"},
                {"name": "Bossini", "floor": "Ground"},
                {"name": "Bright Palace", "floor": "Ground"},
                {"name": "Budget Shoes", "floor": "Ground"},
                {"name": "C9 Chocolate and Gelato", "floor": "Ground"},
                {"name": "Car Expert", "floor": "Ground"},
                {"name": "CCO.W", "floor": "Ground"},
                {"name": "Chase Sheil", "floor": "Ground"},
                {"name": "Chemist Warehouse", "floor": "Ground"},
                {"name": "China Bar", "floor": "Ground"},
                {"name": "Chipmunks", "floor": "Ground"},
                {"name": "Costco", "floor": "Ground"},
                {"name": "Creative Iris Photography", "floor": "Ground"},
                {"name": "Crown Duty Free", "floor": "Ground"},
                {"name": "Dan Murphys", "floor": "Ground"},
                {"name": "Daybreak Cafe", "floor": "Ground"},
                {"name": "District Office 3", "floor": "Ground"},
                {"name": "District Offices 2", "floor": "Ground"},
                {"name": "District Pizzeria", "floor": "Ground"},
                {"name": "Docklands Primary School", "floor": "Ground"},
                {"name": "Dohtonbori Okonomiyaki", "floor": "Ground"},
                {"name": "Dream In Style", "floor": "Ground"},
                {"name": "Dreamskape", "floor": "Ground"},
                {"name": "East West Eatery", "floor": "Ground"},
                {"name": "East West Marketplace", "floor": "Ground"},
                {"name": "EB Games", "floor": "Ground"},
                {"name": "Elegance By Dr Tony Truong", "floor": "Ground"},
                {"name": "Endota Wellness College", "floor": "Ground"},
                {"name": "Fantastic Variety", "floor": "Ground"},
                {"name": "Fila", "floor": "Ground"},
                {"name": "Flight Experience", "floor": "Ground"},
                {"name": "Froyolicious", "floor": "Ground"},
                {"name": "Fukutontei Ramen", "floor": "Ground"},
                {"name": "Gap Maps", "floor": "Ground"},
                {"name": "Gelateria On The Docks", "floor": "Ground"},
                {"name": "Gift & Book Station", "floor": "Ground"},
                {"name": "Giraffe Early Learning Centre", "floor": "Ground"},
                {"name": "Gozleme King", "floor": "Ground"},
                {"name": "H&M Ground Floor", "floor": "Ground"},
                {"name": "Habitat Mind Body", "floor": "Ground"},
                {"name": "Hana Sushi", "floor": "Ground"},
                {"name": "Hidden Agenda", "floor": "Ground"},
                {"name": "House Down Under", "floor": "Ground"},
                {"name": "Hoyts", "floor": "Ground"},
                {"name": "Hype DC", "floor": "Ground"},
                {"name": "Imaginator", "floor": "Ground"},
                {"name": "Kaisercraft", "floor": "Ground"},
                {"name": "Kalaro Studio", "floor": "Ground"},
                {"name": "Kathmandu", "floor": "Ground"},
                {"name": "KFC", "floor": "Ground"},
                {"name": "Kindred Camera", "floor": "Ground"},
                {"name": "Krabby's Crab Boil", "floor": "Ground"},
                {"name": "Kreative Human", "floor": "Ground"},
                {"name": "Love Eyebrows", "floor": "Ground"},
                {"name": "Luoda Property", "floor": "Ground"},
                {"name": "Luxm Hair", "floor": "Ground"},
                {"name": "Magnet Gallery", "floor": "Ground"},
                {"name": "Marriott Hotel Ground Floor", "floor": "Ground"},
                {"name": "Marrybrown", "floor": "Ground"},
                {"name": "MCR Moda Crise Menswear", "floor": "Ground"},
                {"name": "Melbourne College Of Hair And Beauty", "floor": "Ground"},
                {"name": "Melbourne Ice", "floor": "Ground"},
                {"name": "Miniso", "floor": "Ground"},
                {"name": "Miss Pings", "floor": "Ground"},
                {"name": "Mojo Jojo", "floor": "Ground"},
                {"name": "My Touch Mobile", "floor": "Ground"},
                {"name": "Nails Avenue", "floor": "Ground"},
                {"name": "Nandos", "floor": "Ground"},
                {"name": "Natural Velocity", "floor": "Ground"},
                {"name": "Nesuto Ground Floor", "floor": "Ground"},
                {"name": "O'Brien Icehouse", "floor": "Ground"},
                {"name": "Old Man Pho", "floor": "Ground"},
                {"name": "Orientcare & Massage", "floor": "Ground"},
                {"name": "Palgong Tea", "floor": "Ground"},
                {"name": "Penny Cafe", "floor": "Ground"},
                {"name": "Petal Back", "floor": "Ground"},
                {"name": "Peter Jackson", "floor": "Ground"},
                {"name": "Peter Rowland", "floor": "Ground"},
                {"name": "Pure Beauty And Spa", "floor": "Ground"},
                {"name": "Racing Victoria", "floor": "Ground"},
                {"name": "Rotary Book Club", "floor": "Ground"},
                {"name": "Saboteurs", "floor": "Ground"},
                {"name": "San Churro", "floor": "Ground"},
                {"name": "Seme Di Fico", "floor": "Ground"},
                {"name": "Seoul Garden Korean BBQ Buffet", "floor": "Ground"},
                {"name": "Shall We Coffee", "floor": "Ground"},
                {"name": "Sketchers", "floor": "Ground"},
                {"name": "Souvenirs Direct", "floor": "Ground"},
                {"name": "Soy Toy Club", "floor": "Ground"},
                {"name": "Sporting House Direct", "floor": "Ground"},
                {"name": "Spud Bar", "floor": "Ground"},
                {"name": "Star Car Wash", "floor": "Ground"},
                {"name": "STEM Birds", "floor": "Ground"},
                {"name": "Studio XL-XS", "floor": "Ground"},
                {"name": "Subway", "floor": "Ground"},
                {"name": "Sushi Yuzen", "floor": "Ground"},
                {"name": "Tatts", "floor": "Ground"},
                {"name": "The Coffee Club", "floor": "Ground"},
                {"name": "The Digital Picnic", "floor": "Ground"},
                {"name": "The District Management Office", "floor": "Ground"},
                {"name": "The Mbassy Dance Studio", "floor": "Ground"},
                {"name": "The Nanny Exhibit", "floor": "Ground"},
                {"name": "The Pancake Parlour", "floor": "Ground"},
                {"name": "Tho Tho's - The Pink Rabbit", "floor": "Ground"},
                {"name": "Toy World", "floor": "Ground"},
                {"name": "Travelite", "floor": "Ground"},
                {"name": "Underrated", "floor": "Ground"},
                {"name": "UNIQLO", "floor": "Ground"},
                {"name": "Urban Ally Brewery", "floor": "Ground"},
                {"name": "Valley Girl", "floor": "Ground"},
                {"name": "WM Massage", "floor": "Ground"},
                {"name": "Woolworths", "floor": "Ground"},
                {"name": "Xgimi", "floor": "Ground"},
                {"name": "Yassas", "floor": "Ground"},
                {"name": "Yesign Design", "floor": "Ground"},
                {"name": "Yunique Tea", "floor": "Ground"},
                {"name": "Zero Latency", "floor": "Ground"},
                {"name": "Zylish", "floor": "Ground"}
            ]
         """,
        llm=llm,
    )
    result = await agent.run()
    print(result)

asyncio.run(main())